### ISSUE TITLE
how to write test case？

### ISSUE THREAD

**Issue by a112121788** [macacajs/macaca-cli#15]
平台： android
情况：
页面用了一个listview做的。
怎么实现点击listview上的某一个item上文字为 "登录" 的 textview的测试。
怎么实现点击listview上的某一个item上文字为 "确定" 的 Button的测试。

**Comment by tsj1107** [comment]
```
it('#1 login success', function() {
    return driver
      .login('12345678', '111111')
      .sleep(1000)
      .elementById('login-btn')
      .tap()
  });
```

更多API可见 [http://macacajs.github.io/macaca/guide.html#/mobile-docs?_k=bdda55](http://macacajs.github.io/macaca/guide.html#/mobile-docs?_k=bdda55)

**Comment by a112121788** [comment]
不行 解决不了。

**Comment by tsj1107** [comment]
是这样的 你需要对自己的app写一个自己的webdriver-client 可以参考这个例子[https://github.com/xudafeng/webdriver-client](https://github.com/xudafeng/webdriver-client)

具体到你这个问题 可参考这行代码[https://github.com/xudafeng/webdriver-client/blob/master/lib/mobile/android/login.js#L24](https://github.com/xudafeng/webdriver-client/blob/master/lib/mobile/android/login.js#L24)

**Comment by a112121788** [comment]
理解了。
