### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by loneyao** [macacajs/macaca-cli#20]
const path = require('path');
const wd = require('wd'); // 引用 wd 模块

describe('macaca mobile sample', function() {
  this.timeout(5 \* 60 \* 1000); // mocha 设置超时时间

  var driver = wd.promiseChainRemote({ // 初始化 webdriver
    host: 'localhost',
    port: 3456
  });

  before(function() { 
    return driver.init({ 
    platformName: 'iOS',  
    udid: 'd8f6f0875320116fc5946b020a84b6dccba9d815',
    bundleId: 'com.mosheberman.Surfboard'
    });
 });

  after(function() { // 所有测试用例的统一后置动作
    return driver 
      .sleep(1000)
      .quit();
  });

  it('#1 should login success', function() {
      return driver
      .elementByName('Tap Here To Surf Again')
      .click()
      .sleep(3000)
      .takeScreenshot(path);

  });

});

Last login: Tue Apr 12 15:53:23 on ttys000
clydeiMac:~ cly$ cd /Users/cly/Desktop/macaca-test/
clydeiMac:macaca-test cly$ make test
platform= macaca run --server --verbose

---
-  version 1.0.13 is outdate           *
-  run: npm i -g macaca-client@1.0.10  *
  ****************************************

> > index.js:62:12 [master] pid:39068 webdriver server start with config:
> >  { port: 3456,
> >   ip: '192.168.3.70',
> >   host: 'clydeiMac.local',
> >   loaded_time: '2016-04-12 16:06:34' }
> > middlewares.js:31:10 [master] pid:39068 base middlewares attached
> > router.js:101:10 [master] pid:39068 router set
> > webdriver sdk launched
> > 
> >   macaca mobile sample
> > responseHandler.js:24:12 [master] pid:39068 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"iOS","udid":"d8f6f0875320116fc5946b020a84b6dccba9d815","bundleId":"com.mosheberman.Surfboard","browserName":"firefox","version":"","javascriptEnabled":true,"platform":"ANY"}}
> > session.js:22:10 [master] pid:39068 Creating session, sessionId: a4307991-cae2-4656-8e5b-5e6296358984.
> > responseHandler.js:56:12 [master] pid:39068 Send Error Respone to Client TypeError: Cannot read property 'substring' of undefined
> > responseHandler.js:62:14 [master] pid:39068 TypeError: Cannot read property 'substring' of undefined
> >     at Function._.sleep._.retry._.waitForCondition._.exec._.spawn.child.on._.configApp (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/webdriver-server/lib/common/helper.js:174:10)
> >     at WebdriverServer.start (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/webdriver-server/lib/server/index.js:39:16)
> >     at next (native)
> >     at onFulfilled (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:65:19)
> >     at /Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:54:5
> >     at Object.co (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:50:10)
> >     at Object.toPromise (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:118:63)
> >     at next (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:99:29)
> >     at onFulfilled (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:69:7)
> >     at /Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:54:5
> >     at Object.co (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:50:10)
> >     at Object.toPromise (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:118:63)
> >     at next (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:99:29)
> >     at onFulfilled (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:69:7)
> >     at /Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:54:5
> >     at Object.co (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:50:10)
> > responseHandler.js:81:14 [master] pid:39068 Unexcepted error TypeError

  InternalServerError: Internal Server Error
      at Object.module.exports.throw (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/webdriver-server/node_modules/koa/lib/context.js:91:23)
      at Object.module.exports (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/webdriver-server/lib/server/responseHandler.js:82:17)
      at throw (native)
      at onRejected (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:81:24)
      at process._tickCallback (node.js:369:9)

> >   1) "before all" hook
> > responseHandler.js:24:12 [master] pid:39068 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session, jsonBody: {}
> > responseHandler.js:48:14 [master] pid:39068 Send HTTP Respone to Client: {"sessionId":"","status":0}
> > 
> >   0 passing (4s)
> >   1 failing
> > 
> >   1) macaca mobile sample "before all" hook:
> >      Error: [init({"platformName":"iOS","udid":"d8f6f0875320116fc5946b020a84b6dccba9d815","bundleId":"com.mosheberman.Surfboard"})] The environment you requested was unavailable.
> >       at endReadableNT (_stream_readable.js:905:12)
> > 
> > Test completed!

**Comment by loneyao** [comment]
我是想用真机来试下

**Comment by lengyao88** [comment]
解决了

**Comment by xudafeng** [comment]
@lengyao88 issue后面统一提在 https://github.com/alibaba/macaca/issues
