### ISSUE TITLE
页面的值不匹配时提交到 服务端

### ISSUE THREAD

**Issue by zanjs** [macacajs/macaca-cli#43]
## 有这样一个场景

在测试页面的数据显示是否正确的时候，

如果匹配不正确需要把当前页面的 url 和 页面的数据 提交到 一个错误收集的 服务端，以便服务端好接收到。

如何发起提交呢？

**Comment by xudafeng** [comment]
@zanjs 可以明确下什么服务端吗？

**Comment by zanjs** [comment]
@xudafeng  

在使用 `macaca-cli` 给 `www.xxx.com` 网站做全面的 测试服务，当测试到一个页面发现错误或者数据不对时，把当前页面的 url 地址 和错误信息 发起一个 `ajax`  提交 到 `error.xxx.com` 该服务下。

测试脚本每天自动跑着，开发人员只需在后台 `error.xxx.com` 查看有木有 测试脚本提交上来的 错误信息

**Comment by xudafeng** [comment]
@zanjs 进qq群讨论287162474
