### ISSUE TITLE
1.10更新后找不到driver

### ISSUE THREAD

**Issue by bingzheyuan** [macacajs/macaca-cli#45]
node：v4.2.1
npm: 2.14.7
OS: win7 x64

macaca 1.0.35的时候，使用`macaca install electron`可以安装好electron driver,desctop测试能运行。更新1.1.0以后，`macaca install`不存在了，`npm i --save-dev macaca-electron`后，使用`macaca doctor`看不到electron driver。然后测试报错说缺少driver。

`-g` 安装macaca-electron后并且升级 node到4.4.7后测试能够运行了，但是`macaca doctor`依然无法显示driver.

**Comment by xudafeng** [comment]
http://macacajs.github.io/macaca/environment-setup.html

npm i macaca-electron -g

**Comment by bingzheyuan** [comment]
昨天`-g` 安装macaca-electron已经能使测试运行，macaca-test-sample 项目中的makefile用的是local install的macaca-electron, [传送门](https://github.com/macacajs/macaca-test-sample/blob/master/Makefile#L27)，测试成功是因为用的macaca也是local install 的？<br>`doctor`命令不显示`-g` 安装的macaca-electron，是BUG么？

**Comment by xudafeng** [comment]
@bingzheyuan 项目中的Make主要是用来跑CI的。全局用直接 macaca run就行

**Comment by xudafeng** [comment]
@bingzheyuan 如果你当前目录安装过的话，就不会去全局找，看你怎么选择

**Comment by bingzheyuan** [comment]
这就是我的问题，我把全局的uninstall,只剩下local的macaca-electron，测试就报错，说the environment you requested is unavailable.

**Comment by xudafeng** [comment]
@bingzheyuan 那就应该用 make travis-pc

**Comment by xudafeng** [comment]
https://travis-ci.org/xudafeng/macaca-test-sample-android-ci/builds/131592671#L1615

**Comment by bingzheyuan** [comment]
不知道是不是windows 的问题，windows也没有make, 我测不了make travis-pc

> npm install macaca-electron --save-dev
> ${npm_bin}/macaca doctor 

是指local安装`macaca-electron`再使用global的`macaca doctor`对吧？
我在windows上，会出现之前的报错。
不过这个错没什么关系，可以用-g安装解决。
谢谢你的回答了。
